spot: 
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  front_left_shoulder_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: front_left_shoulder_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  front_right_shoulder_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: front_right_shoulder_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}
  
  rear_left_shoulder_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: rear_left_shoulder_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  rear_right_shoulder_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: rear_right_shoulder_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  front_left_arm_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: front_left_arm_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  front_right_arm_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: front_right_arm_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}
  
  rear_left_arm_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: rear_left_arm_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  rear_right_arm_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: rear_right_arm_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  front_left_knee_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: front_left_knee_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  front_right_knee_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: front_right_knee_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}
  
  rear_left_knee_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: rear_left_knee_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  rear_right_knee_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: rear_right_knee_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  front_left_leg_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: front_left_leg_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  front_right_leg_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: front_right_leg_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}
  
  rear_left_leg_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: rear_left_leg_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}

  rear_right_leg_joint_controller: 
    type:  velocity_controllers/JointVelocityController
    joint: rear_right_leg_joint
    pid: {p: 50.0, i: 0.001, d: 20.0}


